### ISSUE TITLE
Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by krhubert** [sindresorhus/electron-config#9] opened 2017-01-17 07:50 UTC
Hi,

I'm trying to build app using electron config but I have trouble with ```npm run package``` using this module.

```
$ git clone https://github.com/chentsulin/electron-react-boilerplate
$ cd electron-react-boilerplate
$ npm run dev # GOOD
$ npm run package # GOOD

$ # Import electron-config
$ git diff
--- a/app/main.development.js
+++ b/app/main.development.js
@@ -1,4 +1,5 @@
 import { app, BrowserWindow, Menu, shell } from 'electron';
+import Config from 'electron-config'

 let menu;
 let template;

$ npm run dev # GOOD
$ npm run package # FAILS (both on windows and linux)
# Uncaught Exception:
# TypeError: Cannot read prperty 'filename' of undefined
```

**Comment by krhubert** [comment] 2017-01-17 08:03
```
$ grep -n filename node_modules/conf/index.js
12:delete require.cache[__filename];
14:const parentDir = path.dirname(module.parent.filename);
$ ./release/linux-unpacked/app
{ exports: {},
  id: 300,
  loaded: false,
  deprecate: [Function],
  paths: [],
  children: [],
  webpackPolyfill: 1 }
$ # no parent
```

**Comment by SamVerschueren** [comment] 2017-01-17 08:09
I don't think this module can be used inside the rendering process of Electron when building with things like webpack. Not sure though, I'm quite new to Electron as well.
What I do know though is that bundlers like Webpack or SystemJS don't implement `module.parent` because it's a quite expensive task to keep track of in a browser.
Probably @sindresorhus knows more about this though...

**Comment by krhubert** [comment] 2017-01-17 08:38
> I don't think this module can be used inside the rendering process of Electron when building with things like webpack. Not sure though, I'm quite new to Electron as well.

It is not. This module was used in electron main process. 

> What I do know though is that bundlers like Webpack or SystemJS don't implement module.parent because it's a quite expensive task to keep track of in a browser.

Yep, but I think it's an issue if you can't use the module in a production environment.
I can comment those lines out but wanted to create this issue to solve pmb.

**Comment by SamVerschueren** [comment] 2017-01-17 08:41
Strange, if it's used in the main process it should work because Webpack isn't touching those, right? Not sure what's wrong then, I've used this module successfully in an Electron application. Is the code open source, might be easier to track down the issue?

**Comment by krhubert** [comment] 2017-01-17 08:48
> Is the code open source, might be easier to track down the issue?

You have instruction in the issue, just:

```git clone https://github.com/chentsulin/electron-react-boilerplate```

and add ```import Config from 'electron-config'``` in the ```main.development.js``` file

**Comment by SamVerschueren** [comment] 2017-01-17 09:07
Odd, there is not much to it. It works on macOS. If I find some time later today I will test it on windows.

**Comment by hordurk** [comment] 2017-02-07 12:02
@krhubert When using that boilerplate, for some dependencies you need to add them to package.json within app/ directory as well as the top-level one. I was getting that error and that fixed it for me.

**Comment by chenlongkk** [comment] 2017-02-20 14:23
I have the same issue, does anyone knows how to solve this ?

**Comment by MatthieuLemoine** [comment] 2017-03-17 15:16
Duplicate issue of #3 ?

**Comment by sindresorhus** [comment] 2017-04-30 09:38
Duplicate of #3

**Closed by sindresorhus** 2017-04-30 09:38 UTC
